# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-08 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='student_id',
            field=models.IntegerField(default=0),
        ),
    ]
