# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-13 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='num_people',
            field=models.IntegerField(verbose_name=(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_number',
            field=models.SmallIntegerField(choices=[(0, '세미나실'), (1, '라운지'), (2, '갤러리')], default=0),
        ),
    ]
