# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-08 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20180308_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_accept',
            field=models.BooleanField(default=False),
        ),
    ]
