# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-13 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20180313_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='tel_num',
            field=models.IntegerField(max_length=30),
        ),
    ]
