# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-14 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20180313_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rend_time',
            field=models.SmallIntegerField(choices=[(0, '9:00 ~ 10:00'), (1, '10:00 ~ 11:00'), (2, '11:00 ~ 12:00'), (3, '12:00 ~ 13:00'), (4, '13:00 ~ 14:00'), (5, '14:00 ~ 15:00'), (6, '15:00 ~ 16:00'), (7, '16:00 ~ 17:00'), (8, '17:00 ~ 18:00'), (9, '18:00 ~ 19:00'), (10, '19:00 ~ 20:00')], default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='return_time',
            field=models.SmallIntegerField(choices=[(0, '9:00 ~ 10:00'), (1, '10:00 ~ 11:00'), (2, '11:00 ~ 12:00'), (3, '12:00 ~ 13:00'), (4, '13:00 ~ 14:00'), (5, '14:00 ~ 15:00'), (6, '15:00 ~ 16:00'), (7, '16:00 ~ 17:00'), (8, '17:00 ~ 18:00'), (9, '18:00 ~ 19:00'), (10, '19:00 ~ 20:00')], default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_number',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='tel_num',
            field=models.IntegerField(),
        ),
    ]
